apiVersion: apps/v1
kind: Deployment
metadata:
  name: yeet-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yeet
  template:
    metadata:
      labels:
        app: yeet
    spec:
      containers:
      - name: yeet
        image: gcr.io/personal-147902/yeet:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: yeet
spec:
  type: NodePort
  selector:
    app: yeet
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9376
      nodePort: 30036
---
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service
subsets:
  - addresses:
      - ip: 192.0.2.42
    ports:
      - port: 9376