# fly.toml file generated for summer-water-7978 on 2022-08-24T19:31:36-06:00

app = "summer-water-7978"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"
  POWER_METERS_DB_PATH = "/data/power_meters.db"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  source="power_mania_vol"
  destination="/data"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
