[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = { version = "0.2.1", features = [] }
itertools = "0.13.0"
# ahash = "0.8.7"
# arrayvec = "0.7.4"
