[package]
name = "lumen2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.13", features = ["blocking"] }
serde = { version = "1.0.148", features = ["derive"] }
serde-xml-rs = "0.6.0"
serde_json = "1.0.89"
